# Generated by Django 4.2.27 on 2026-01-13 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='reports/')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('report_name', models.CharField(default='Routine Check', max_length=100)),
                ('blood_pressure', models.IntegerField(default=120)),
                ('sugar', models.IntegerField(default=100)),
                ('cholesterol', models.IntegerField(default=200)),
                ('hemoglobin', models.FloatField(default=13.5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
